---
title: "Basic Inferential Data Analysis On Tooth Growth In Vitamin C Supplemented Guinea Pigs"
author: "Jon Taylor"
date: "September 20, 2016"
output: pdf_document
---

#Overview

We are going to explore  a dataset where a scientist compared how dosage (0.5, 1.0, 2.0) 
and form of Vitamin C (supplement, orange juice) affected tooth length in 
guinea pigs.

#Summary

First lets load the data and see how Tooth length is ditributed based on dose
and form of Vitamin C.

```{R}
#1. Load the ToothGrowth data and perform some basic exploratory data analyses

data(ToothGrowth)
head(ToothGrowth)

#Plot length vs dose and length vs supp
par("mfcol"=c(1,2))
boxplot(ToothGrowth$len ~ ToothGrowth$dose, xlab="Dose", ylab="Tooth Length")
plot(ToothGrowth$len ~ ToothGrowth$supp)
```


```{R}

#2. Provide a basic summary of the data.

summary(ToothGrowth)

mean(ToothGrowth$len[ToothGrowth$supp == "OJ"])
sd(ToothGrowth$len[ToothGrowth$supp == "OJ"])

mean(ToothGrowth$len[ToothGrowth$supp == "VC"])
sd(ToothGrowth$len[ToothGrowth$supp == "VC"])

```

#T-Tests

The box plots show that tooth length may be affected by both dose and form of 
Vitamin C. We should use a t-test to see if thats true. Let's start with the form
of Vitamin C.

```{R}
#3. Use confidence intervals and/or hypothesis tests to compare tooth growth #by supp and dose. (Only use the techniques from class, even if there's other #approaches worth considering)

t.test(ToothGrowth$len~ToothGrowth$supp)

```

The t-test shows a p-value of just over 0.06 which means we cannot reject the null
hypothesis at a 95% confidence interval. However, it is close, so further 
experimentation may be worth pursuing. 

Now let's do the same for the dose levels.
```{R}

t.test(ToothGrowth$len[ToothGrowth$dose==2], ToothGrowth$len[ToothGrowth$dose==0.5])

t.test(ToothGrowth$len[ToothGrowth$dose==2], ToothGrowth$len[ToothGrowth$dose==1])

t.test(ToothGrowth$len[ToothGrowth$dose==1], ToothGrowth$len[ToothGrowth$dose==0.5])
```

The results show that all of the dosage levels are different than one another.
This leads us to reject the null hypothesis that Vitamin C dosage has no effect 
on tooth length at the 95% confidence interval.

#Assumptions

The independent two group t-test relies on assumptions that the dependent 
variable is normally distributed which we will test below.

```{R}
#4.State your conclusions and the assumptions needed for your conclusions.

#Assumption of normality of the dependent variable
par("mfcol"=c(1,1))
hist(ToothGrowth$len)
qqnorm(ToothGrowth$len) #looks normal
```

The results show that the distribution is appears to be roughly normally distributed.

The independent two group t-test also relies on the assumption that the independent
variables have a homogeneaity of variances. We can test this using bartlett's test.

```{R}
bartlett.test(len ~ interaction(supp,dose), data=ToothGrowth)
```

The results of the bartlett test show that the independent variables have
similar variances.

#Conclusions

Having tested our assumptions of the independent two group t-test, 
we can conclude that Tooth Length is affected by Vitamin C dosage, but not 
by the form in which the Vitamin C is consumed. 
